<?php

function corona_live_tracker_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'corona_live_tracker/corona_live_tracker';
}


function corona_live_tracker_theme($existing, $type, $theme, $path) {
  return [
    'corona_live_tracker' => [
      'variables' => ['countriesdata' => [],'statedata' => [],'traveldata' => []],
    ],
      
    'corona_live_world_map' => [
      'variables' => ['coronaall' => [],],
    ],
  ];
}


